[package]
name = "tms-rs"
version = "0.1.0"
edition = "2024"
rust-version = "1.94"
license = "Unlicense"
readme = "README.md"
repository = "https://github.com/rajayonin/tms-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.104"
thiserror = "2.0.19"
